export const playHtVoices = [
  {
    value: "Matthew",
    name: "Matthew",
    language: "English (US)",
    voiceType: "Standard",
    languageCode: "en-US",
    gender: "Male",
    service: "polly",
    sample: "/matthew.mp3",
  },
  {
    value: "Joanna",
    name: "Joanna",
    language: "English (US)",
    voiceType: "Standard",
    languageCode: "en-US",
    gender: "Female",
    service: "polly",
    sample: "/joanna.mp3",
  },
  {
    value: "Joey",
    name: "Joey",
    language: "English (US)",
    voiceType: "Standard",
    languageCode: "en-US",
    gender: "Male",
    service: "polly",
    sample: "/joey.mp3",
  },
  {
    value: "Salli",
    name: "Salli",
    language: "English (US)",
    voiceType: "Standard",
    languageCode: "en-US",
    gender: "Female",
    service: "polly",
    sample: "/salli.mp3",
  },
];
